name: 'Jira autolink action'
description: 'Automatically create autolink references to all Jira projects'
author: 'invakid404'
inputs:
  ticketPath:
    required: false
    description: "URL path to Jira ticket"
    default: "/browse/<project>-<num>"
  url:
    required: true
    description: "URL to Jira instance"
  username:
    required: true
    description: "Username to use for Jira"
  password:
    required: true
    description: "Password/token to use for Jira"
runs:
  using: 'node12'
  main: 'dist/index.js'
